### ISSUE TITLE
Save view and franch / belgium keyboard

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#1335]
It is possible to save the current zoom level using 1,2,3, ... keys

It is possible for 'force' to save agin using 'SHIFT + 1,2,3,...'.

Problem on a belgian or french keyboard we always need to press shift to access the numbers so we can never reload a saved view.

**Comment by lpatiny** [comment]
@Sebastien-Ahkrin in the debug console if you attach the keydown event and log the event what do you get when you press the key 1 (without shift !!!).

I have

![image](https://user-images.githubusercontent.com/1484241/151012416-10d4da24-2e37-46cb-8f4e-b37e00cf8c38.png)

**Comment by targos** [comment]
You can use this page: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

**Comment by targos** [comment]
On my keyboard (dvorak) I have this (first without shift, then with shift):

```
KeyboardEvent: key='1' | code='Digit1'

KeyboardEvent: key='Shift' | code='ShiftRight'
KeyboardEvent: key='!' | code='Digit1'
```

**Comment by lpatiny** [comment]
Ok easy thanks. I mainly wonder indeed what is the `code` for the key '1' on a french keyboard when you don't press shift.

**Comment by targos** [comment]
And on the num pad:

```
KeyboardEvent: key='1' | code='Numpad1'

KeyboardEvent: key='Shift' | code='ShiftLeft'
KeyboardEvent: key='End' | code='Numpad1'
```

**Comment by Sebastien-Ahkrin** [comment]
On my keyboard: 

Numpad:
```
KeyboardEvent: key='1' | code='Numpad1'
```
Classic key:
```
KeyboardEvent: key='&' | code='Digit1' (while i only press the "1" button)
```
To create the "1" char
```
KeyboardEvent: key='Shift' | code='ShiftRight'
KeyboardEvent: key='1' | code='Digit1'
```

**Comment by lpatiny** [comment]
Ok then to 'save' the view we should check if  code='Digit1' and shift is not pressed and to update the view we should check  code='Digit1' and shift is pressed.

**Comment by targos** [comment]
By the way, on my computer the "view recall" doesn't work:

```
react_devtools_backend.js:4045 
        
       TypeError: Cannot add property 0abwvynpah97, object is not extensible
    at initZoomManager (Zoom1DManager.ts:62:25)
    at Object.getScale (Zoom1DManager.ts:67:11)
    at setZoom (Zoom.ts:83:55)
    at applyKeyPreferencesHandler (PreferencesActions.ts:166:32)
    at innerSpectrumReducer (Reducer.ts:700:14)
    at immer.esm.js:1:16024
    at C.produce (immer.esm.js:1:16172)
    at immer.esm.js:1:15978
    at Object.Fi [as useReducer] (react-dom.profiling.min.js:161:447)
    at Object.ae.useReducer (react.production.min.js:23:173)
    at NMRium (NMRium.tsx:220:29)
```

**Comment by targos** [comment]
> Ok then to 'save' the view we should check if code='Digit1' and shift is not pressed and to update the view we should check code='Digit1' and shift is pressed.

But it has to be using it already, no? If not, how can it work on multiple layouts today?

**Comment by lpatiny** [comment]
> But it has to be using it already, no? If not, how can it work on multiple layouts today?

Most of the time we will not update a saved view but only recall a view (so we would never do SHIFT + 1).

multiple layouts you mean 1D and 2D ?

When we have 1D and 2D we jump to the corresponding set of spectra. So the idea is that we can save in a 1D a zoom level with '1', then go to check some 2D stuff and if we press on '1' we go back on the zoom in the 1D.

**Comment by targos** [comment]
I mean multiple keyboard layouts. Shift+1 is for the exclamation point on my keyboard and it works as well as with your keyboard where Shift+1 is another character.

**Comment by lpatiny** [comment]
> I mean multiple keyboard layouts. Shift+1 is for the exclamation point on my keyboard and it works as well as with your keyboard where Shift+1 is another character.

Indeed I don't know.

BTW it should work with NumPad in the same way as with the keyboard keys.

**Comment by Sebastien-Ahkrin** [comment]
Hi @lpatiny.
I tryied to reproduce the error with my keyboard but, it's look like i can't reproduce it.
For my keyboard everything works as expected :/

**Comment by lpatiny** [comment]
@ReinerD This seems strange cause it works on french keyboard. Are the Belgian keyboards that different ??

Please could you check again with the last dev.nmrium.org version ?

If it does not work please could you give us the result of pressing the key '1' with and without shift on the page 

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

![image](https://user-images.githubusercontent.com/1484241/151214958-34cbd0e0-16c9-46cb-99d9-e6947d2bd535.png)

**Comment by ReinerD** [comment]
tested it again (dev.nmrium.org, firefox, ubuntu). The zoom keys actually _do_work using the keys the numbers figure on (1,&,) , 2,é,@; etc).  I managed to assign different zoom regions to & et é, alternate back and forth between them and modify one of them using shift.

**Comment by ReinerD** [comment]
tested also on OSX (chrome): works as well (caps are here 1,&,;2,é,ë).
I didn't realize before that the zoom regions are for a specific spectrum - so, they allow to easily switch between spectra - nice.

**Comment by ReinerD** [comment]
it may nevertheless be useful to mention in the documentation that it works with the keys holding the numbers, not the number characters as such

**Comment by lpatiny** [comment]
@ReinerD would you help us with the documentation ? I could show you how to edit it and improve it.

**Comment by lpatiny** [comment]
I think there is even no information at all in the documentation about this feature ...

**Comment by ReinerD** [comment]
Sure, I'd be happy to help
