### ISSUE TITLE
Crash when selecting manual range in .nmrium file

### ISSUE THREAD

**Issue by jschneidewind** [cheminfo/nmrium#1555]
# Description

There seems to be an issue when manually selecting ranges in `.nmrium` files. When an `.nmrium` file is opened and a range is selected, nmrium crashes. Automatic range selection works normally, however. A similar problem seems to occur when working with the development version at [dev.nmrium.org](dev.nmrium.org), although with a slightly different error message (see below)

# Reproduction

When the attached ZIP file (RDI-103.zip, zipped Bruker file) is opened, manual range selection works normally. However, when the file is saved as an `.nmrium` file and opened again, manual range selection results in the error message shown below. Using compressed/uncompressed `.nmrium` files or using pretty format does not seem to make a difference. Tested on Windows (Edge and Chrome) as well as macOS (Chrome).

# Error message regular nmrium.org

```bash
e.subarray is not a function

TypeError: e.subarray is not a function
    at https://www.nmrium.org/_next/static/chunks/282.fc1ef91134e46700.js:16:43994
    at Yr (https://www.nmrium.org/_next/static/chunks/282.fc1ef91134e46700.js:16:44289)
    at https://www.nmrium.org/_next/static/chunks/282.fc1ef91134e46700.js:16:217828
    at https://www.nmrium.org/_next/static/chunks/282.fc1ef91134e46700.js:16:217901
    at https://www.nmrium.org/_next/static/chunks/762-d4cd0bf867cd061e.js:1:25631
    at e.produce (https://www.nmrium.org/_next/static/chunks/762-d4cd0bf867cd061e.js:1:25779)
    at https://www.nmrium.org/_next/static/chunks/762-d4cd0bf867cd061e.js:1:25585
    at Object.co [as useReducer] (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:60645)
    at t.useReducer (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:125348)
    at aI (https://www.nmrium.org/_next/static/chunks/282.fc1ef91134e46700.js:2969:237)
    at oo (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:59416)
    at Wo (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:68983)
    at Ku (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:112707)
    at Li (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:98957)
    at Ni (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:98885)
    at Pi (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:98748)
    at bi (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:95714)
    at https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:45208
    at t.unstable_runWithPriority (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:129354)
    at Ql (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:44985)
    at Yl (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:45153)
    at Kl (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:45088)
    at Ui (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:104852)
    at t.unstable_runWithPriority (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:129354)
    at Ql (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:44985)
    at Fi (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:104127)
    at Fe (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:116412)
    at Xt (https://www.nmrium.org/_next/static/chunks/framework-bb5c596eafb42b22.js:1:23677)
```

# Error message dev.nmrium.org

```bash
x.subarray is not a function

TypeError: x.subarray is not a function
    at detectSignal (https://dev.nmrium.org/assets/index.dbbb5d22.js:1108:12)
    at addRange (https://dev.nmrium.org/assets/index.dbbb5d22.js:2781:18)
    at handleAddRange (https://dev.nmrium.org/assets/index.dbbb5d22.js:4867:5)
    at innerSpectrumReducer (https://dev.nmrium.org/assets/index.dbbb5d22.js:7466:14)
    at https://dev.nmrium.org/assets/vendor.87d714d2.js:24442:35
    at e3.produce (https://dev.nmrium.org/assets/vendor.87d714d2.js:24450:16)
    at https://dev.nmrium.org/assets/vendor.87d714d2.js:24440:21
    at Object.ri$1 [as useReducer] (https://dev.nmrium.org/assets/vendor.87d714d2.js:3913:185)
    at Object.react_production_min.useReducer (https://dev.nmrium.org/assets/vendor.87d714d2.js:340:22)
    at InnerNMRium (https://dev.nmrium.org/assets/index.dbbb5d22.js:33318:43)
    at ii$1 (https://dev.nmrium.org/assets/vendor.87d714d2.js:3836:8)
    at Oj$1 (https://dev.nmrium.org/assets/vendor.87d714d2.js:4988:8)
    at Hl (https://dev.nmrium.org/assets/vendor.87d714d2.js:7254:98)
    at Gl (https://dev.nmrium.org/assets/vendor.87d714d2.js:6814:144)
    at Fl (https://dev.nmrium.org/assets/vendor.87d714d2.js:6806:5)
    at tl$1 (https://dev.nmrium.org/assets/vendor.87d714d2.js:6788:7)
    at yl (https://dev.nmrium.org/assets/vendor.87d714d2.js:6484:8)
    at rl$1 (https://dev.nmrium.org/assets/vendor.87d714d2.js:6420:60)
    at J2 (https://dev.nmrium.org/assets/vendor.87d714d2.js:460:20)
    at MessagePort.R2 (https://dev.nmrium.org/assets/vendor.87d714d2.js:490:14)
```

I really enjoy using nmrium and am happy to provide additional information if that may be helpful.

[RDI-103.zip](https://github.com/cheminfo/nmrium/files/8709157/RDI-103.zip)

**Comment by lpatiny** [comment]
@jschneidewind Thanks for this great bug report with clear explanation ! Seems you know really well NMRium and many subtleties !

@hamed-musallam We have an issue is that in order to improve the speed of processes I'm using 'subarray' but this method only exists on typed array.

I think when we are loading .nmrium files with simply 'JSON.parse' and therefore we have normal javascript arrays that don't have this subarray method.

Please could you convert all the array in data (x, y, re, im) after parsing the JSON to typed array using something like

`data.x = Float64Array.from(data.x)`

I think this should solve this issue.

**Comment by lpatiny** [comment]
@jschneidewind It is now available on https://dev.nmrium.org and you can check if everything is ok for you.
