### ISSUE TITLE
Critical error in resizing range

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2806]
In some case 'signals' can be undefined and I guess this should rather be an empty array.

This leads to numerous crashes of NMRium.

![2023-12-15 08 20 26](https://github.com/cheminfo/nmrium/assets/1484241/a5a68003-6010-465e-bf84-4b71c4dcbb41)

nmr-processing.mjs:2 Uncaught TypeError: Cannot read properties of undefined (reading 'signals')
    at lg (nmr-processing.mjs:2:357411)
    at i3 (nmr-processing.mjs:2:353865)
    at lu (nmr-processing.mjs:2:357481)
    at changeRange.js:27:9
    at changeRange.js:29:1
    at RangesActions.js:231:1
    at immer.mjs:557:1
    at Object.produce (immer.mjs:570:1)
    at immer.mjs:557:1
    at Object.a_ [as useReducer] (react-dom.production.min.js:170:418)
    at react.production.min.js:25:257
    at RC (NMRiumStateProvider.js:18:34)
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at i (react-dom.production.min.js:292:18)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oP (react-dom.production.min.js:273:239)
    at r8 (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262
lg @ nmr-processing.mjs:2
i3 @ nmr-processing.mjs:2
lu @ nmr-processing.mjs:2
(anonymous) @ changeRange.js:27
(anonymous) @ changeRange.js:29
(anonymous) @ RangesActions.js:231
(anonymous) @ immer.mjs:557
(anonymous) @ immer.mjs:570
(anonymous) @ immer.mjs:557
a_ @ react-dom.production.min.js:170
(anonymous) @ react.production.min.js:25
RC @ NMRiumStateProvider.js:18
ak @ react-dom.production.min.js:167
up @ react-dom.production.min.js:197
i @ react-dom.production.min.js:292
oD @ react-dom.production.min.js:280
(anonymous) @ react-dom.production.min.js:280
oO @ react-dom.production.min.js:280
oP @ react-dom.production.min.js:273
r8 @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 21 more frames
Show less
nmr-processing.mjs:2 Uncaught TypeError: Cannot read properties of undefined (reading 'signals')
    at lg (nmr-processing.mjs:2:357411)
    at i3 (nmr-processing.mjs:2:353865)
    at lu (nmr-processing.mjs:2:357481)
    at changeRange.js:27:9
    at changeRange.js:29:1
    at RangesActions.js:231:1
    at immer.mjs:557:1
    at Object.produce (immer.mjs:570:1)
    at immer.mjs:557:1
    at Object.a_ [as useReducer] (react-dom.production.min.js:170:418)
    at react.production.min.js:25:257
    at RC (NMRiumStateProvider.js:18:34)
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at i (react-dom.production.min.js:292:18)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286)
    at r8 (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262
lg @ nmr-processing.mjs:2
i3 @ nmr-processing.mjs:2
lu @ nmr-processing.mjs:2
(anonymous) @ changeRange.js:27
(anonymous) @ changeRange.js:29
(anonymous) @ RangesActions.js:231
(anonymous) @ immer.mjs:557
(anonymous) @ immer.mjs:570
(anonymous) @ immer.mjs:557
a_ @ react-dom.production.min.js:170
(anonymous) @ react.production.min.js:25
RC @ NMRiumStateProvider.js:18
ak @ react-dom.production.min.js:167
up @ react-dom.production.min.js:197
i @ react-dom.production.min.js:292
oD @ react-dom.production.min.js:280
(anonymous) @ react-dom.production.min.js:280
oO @ react-dom.production.min.js:280
oE @ react-dom.production.min.js:271
oP @ react-dom.production.min.js:273
r8 @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 22 more frames
Show less
console.js:36 TypeError: Cannot destructure property 'from' of 'e' as it is undefined.
    at RangesIntegrals.js:37:17
    at xW (RangesIntegrals.js:49:1)
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at i (react-dom.production.min.js:292:18)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286)
    at r8 (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262
(anonymous) @ console.js:36
overrideMethod @ console.js:213
a9 @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
lW @ react-dom.production.min.js:144
uX @ react-dom.production.min.js:261
e @ react-dom.production.min.js:260
(anonymous) @ react-dom.production.min.js:260
oU @ react-dom.production.min.js:283
oP @ react-dom.production.min.js:273
r8 @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 12 more frames
Show less
console.js:36 TypeError: Cannot read properties of undefined (reading 'id')
    at Ranges.js:9:249
    at Array.map (<anonymous>)
    at Ranges.js:9:56
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at uc (react-dom.production.min.js:195:197)
    at i (react-dom.production.min.js:297:85)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286)
    at r8 (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262
(anonymous) @ console.js:36
overrideMethod @ console.js:213
a9 @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
lW @ react-dom.production.min.js:144
uX @ react-dom.production.min.js:261
e @ react-dom.production.min.js:260
(anonymous) @ react-dom.production.min.js:260
oU @ react-dom.production.min.js:283
oP @ react-dom.production.min.js:273
r8 @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 12 more frames
Show less
console.js:36 TypeError: Cannot read properties of undefined (reading 'signals')
    at xh (Peaks.js:19:18)
    at Peaks.js:47:1
    at Object.aq [as useMemo] (react-dom.production.min.js:179:117)
    at react.production.min.js:25:191
    at Peaks.js:38:12
    at Peaks.js:52:1
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at uc (react-dom.production.min.js:195:197)
    at i (react-dom.production.min.js:297:85)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286)
    at r8 (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262
(anonymous) @ console.js:36
overrideMethod @ console.js:213
a9 @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
lW @ react-dom.production.min.js:144
uX @ react-dom.production.min.js:261
e @ react-dom.production.min.js:260
(anonymous) @ react-dom.production.min.js:260
oU @ react-dom.production.min.js:283
oP @ react-dom.production.min.js:273
r8 @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 12 more frames
Show less
console.js:36 TypeError: Cannot read properties of undefined (reading 'signals')
    at generateJGraphData.js:30:34
    at generateJGraphData.js:37:1
    at generateJGraphData.js:80:1
    at generateJGraphData.js:19:1
    at Object.aq [as useMemo] (react-dom.production.min.js:179:117)
    at react.production.min.js:25:191
    at mJ (JGraph.js:25:57)
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at i (react-dom.production.min.js:292:18)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286)
    at r8 (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262
(anonymous) @ console.js:36
overrideMethod @ console.js:213
a9 @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
lW @ react-dom.production.min.js:144
uX @ react-dom.production.min.js:261
e @ react-dom.production.min.js:260
(anonymous) @ react-dom.production.min.js:260
oU @ react-dom.production.min.js:283
oP @ react-dom.production.min.js:273
r8 @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 12 more frames
Show less
console.js:36 TypeError: Cannot read properties of undefined (reading 'from')
    at RangesPanel.js:42:1
    at Array.filter (<anonymous>)
    at RangesPanel.js:42:1
    at Object.aq [as useMemo] (react-dom.production.min.js:179:117)
    at react.production.min.js:25:191
    at RangesPanel.js:33:24
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at uc (react-dom.production.min.js:195:197)
    at i (react-dom.production.min.js:297:85)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286)
    at r8 (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262

**Comment by targos** [comment]
The source of `undefined` is that `mapRanges` returns an empty array here: https://github.com/cheminfo/nmrium/blob/21fde700b375b799907d2b5251161fd5b2109654/src/data/data1d/Spectrum1D/ranges/changeRange.ts#L31-L43

**Comment by lpatiny** [comment]
Reproducing is easy. Just click and release (without moving the mouse) on a resizing border.

![2023-12-15 12 06 30](https://github.com/cheminfo/nmrium/assets/1484241/45cb9dbc-1862-41aa-b137-1273c37ee3dc)
